sources:
  - name: staging
    database: DataWarehouse
    schema: staging
    tables:
      - name: crm_cust_info    #(crm_cust_info, crm_prd_info, crm_sales_details)
      - name: crm_prd_info
      - name: crm_sales_details
      - name: erp_cust_az12
      - name: erp_loc_a101
      - name: erp_px_cat_g1v2   # ( erp_cust_az12, erp_loc_a101, erp_px_cat_g1v2)        

      