dbt_snowflake_proj:
  outputs:
    dev:
      account: AGPKMTD-AUC04067
      database: AIRBNB
      password: Snowflake123123123
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: AHMEDMO123
      warehouse: MY_SECOND_WH
  target: dev
jaffle_shop:
  outputs:
    dev:
      database: DataWarehouse
      host: localhost
      password: password
      port: 5432
      schema: default
      threads: 16
      type: postgres
      user: postgres
  target: dev
pipe:
  outputs:
    dev:
      account: QOOKLEG-XH49346
      database: DataWarehouse
      password: PassWord!
      role: dbt_role
      schema: default
      threads: 1
      type: snowflake
      user: dbt_user
      warehouse: dbt_wh
  target: dev
